export const wishes = [
    {
      id: 1,
      name: 'SD kartica 32GB (2x)',
      link: 'https://www.kupujemprodajem.com/foto-aparati-i-kamere/memorijske-kartice/memorijska-kartica-klasa-10-micro-sd-kartica-32gb/oglas/192666637',
      purchasedBy: null,
      category: 'Elektronika',
      image: '/kartica.webp',
    },
    {
      id: 2,
      name: 'UV majica (2x)',
      link: 'https://www.decathlon.rs/p/365654-380621-muska-majica-sa-uv-zastitom-za-surfovanje.html',
      purchasedBy: 'Anja',
      category: 'Odeća',
      image: '/majica.avif',
    },
    {
      id: 3,
      name: "Majica (XL)",
      link: 'https://rs.beosport.com/ngn-tennis-motion-majica-38042-nvy',
      purchasedBy: null,
      category: 'Odeća',
      image: '/majica.jpg',
    },
    {
      id: 4,
      name: 'Legend farmerke',
      link: 'https://www.legend.rs/model-muske-regular-farmerke-ravnih-nogavica-model-110/17759',
      purchasedBy: null,
      category: 'Odeća',
      image: '/farke.webp',
    },
    {
      id: 5,
      name: 'Bušilica',
      link: 'https://www.kupujemprodajem.com/auto-delovi-i-alati/alati-i-oprema-za-autoservise/hilti-busilica-bosch-800w/oglas/181446229',
      purchasedBy: null,
      category: 'Alat',
      image: '/bosch.webp',
    },
    {
      id: 6,
      name: 'Nadzorna kamera',
      link: 'https://www.tempo-tehnika.rs/artikal/tp-link-kamera-tapo-c310',
      purchasedBy: null,
      category: 'Oprema',
      image: '/kamera.webp',
    },
    {
      id: 7,
      name: 'Set alata',
      link: 'https://www.okov.rs/sr/proizvodi/garnitura-nasadnih-kljuceva-14-551-u-pvc-koferu-neo',
      purchasedBy: null,
      category: 'Alat',
      image: '/kljucevi.png',
    },
  ]